# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVsfy-pwKzvYv70CvYA28U5iRs52bgRj
"""

#!/usr/bin/env python
# coding: utf-8



import random
import matplotlib.pyplot as plt



z=0
count=0
while z<1000000:
    list1=[]
    X=random.uniform(-1,1)
    list1.append(X)
    Y=random.uniform(-1,1)
    list1.append(Y)
    list2=sorted(list1)
    if list2[-1]<.5:
        count+=1
    z+=1





print(f'Probability that max(X and Y)< 1/2 is {count/z}')





x=['simulated','theoretical']
y=[count/z,9/16]
plt.ylim(0,.6)
plt.title('simulated vs theoretical')
plt.ylabel('probability')
plt.bar(x,y,color=['red','blue'])
plt.grid()
plt.show()
plt.savefig('simulated vs theoretical.png')





y


# In[ ]: